// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaL3N4NnJW8ZyxYnd2XX4wz8-nSAlhtfs',
    appId: '1:848896116866:web:e954ea3a570f1ef63f4c9b',
    messagingSenderId: '848896116866',
    projectId: 'note-taking-app-2e7d4',
    authDomain: 'note-taking-app-2e7d4.firebaseapp.com',
    storageBucket: 'note-taking-app-2e7d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA99XJXy6DiYmTLdZjIxc-8LQzTmrHqJIg',
    appId: '1:848896116866:android:6e49c81cdc4d5af73f4c9b',
    messagingSenderId: '848896116866',
    projectId: 'note-taking-app-2e7d4',
    storageBucket: 'note-taking-app-2e7d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaOyHEYTa_en9kncNNvUrJldntWxh-WD4',
    appId: '1:848896116866:ios:6677a453f57759a53f4c9b',
    messagingSenderId: '848896116866',
    projectId: 'note-taking-app-2e7d4',
    storageBucket: 'note-taking-app-2e7d4.appspot.com',
    iosBundleId: 'com.example.noteTakingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaOyHEYTa_en9kncNNvUrJldntWxh-WD4',
    appId: '1:848896116866:ios:6677a453f57759a53f4c9b',
    messagingSenderId: '848896116866',
    projectId: 'note-taking-app-2e7d4',
    storageBucket: 'note-taking-app-2e7d4.appspot.com',
    iosBundleId: 'com.example.noteTakingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaL3N4NnJW8ZyxYnd2XX4wz8-nSAlhtfs',
    appId: '1:848896116866:web:fbd61eea0e17fdd83f4c9b',
    messagingSenderId: '848896116866',
    projectId: 'note-taking-app-2e7d4',
    authDomain: 'note-taking-app-2e7d4.firebaseapp.com',
    storageBucket: 'note-taking-app-2e7d4.appspot.com',
  );
}
